"""
Semantic Matching V4
- User profile structured into specific / generic / redundant interests
- Articles pre-tagged with specific / generic topics (simulated, later via Groq)
- Cosine similarity computed on specific vs specific and generic vs generic separately
- Embeddings: Gemini (gemini-embedding-001)
- Enrichment + profile structuring: Groq (llama-3.1-8b-instant)
"""

import os
import json
import time
import numpy as np
from groq import Groq
from google import genai
from dotenv import load_dotenv

load_dotenv()

# ─── CLIENTS ──────────────────────────────────────────────

GROQ_API_KEY   = os.getenv("GROQ_API_KEY")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

groq_client   = Groq(api_key=GROQ_API_KEY)
gemini_client = genai.Client(api_key=GEMINI_API_KEY)

GROQ_MODEL  = "llama-3.1-8b-instant"
MODEL_EMBED = "gemini-embedding-001"

# ─── USER PROFILE (raw) ───────────────────────────────────

USER_INTERESTS_RAW = [
    "artificial intelligence",
    "startups",
    "tech innovation"
]

# ─── ARTICLES — topics simulated (specific + generic) ─────
# In production: these keys will be generated by Groq from article content

ARTICLES = [
    {
        "id": 1,
        "title": "Google unveils Gemini Ultra 3.0, a major leap in machine learning",
        "topic": "technology",
        "summary": "Google has presented Gemini Ultra 3.0, its new large language model based on deep learning and transformer neural networks. This LLM outperforms GPT-4 on all major AI benchmarks and represents a breakthrough in generative artificial intelligence.",
        "topics": {
            "specific": ["LLM", "Gemini Ultra", "transformer", "deep learning", "GPT-4"],
            "generic":  ["artificial intelligence", "technology", "machine learning"]
        },
        "importance": 9.0,
        "expected": "✅ highly relevant"
    },
    {
        "id": 2,
        "title": "ChatGPT surpasses 500 million active users worldwide",
        "topic": "technology",
        "summary": "OpenAI announces that ChatGPT, its AI assistant powered by large language models, has reached 500 million active users globally. This milestone reflects the massive adoption of generative AI and LLM-based tools by the general public.",
        "topics": {
            "specific": ["ChatGPT", "OpenAI", "LLM", "generative AI"],
            "generic":  ["artificial intelligence", "technology", "user adoption"]
        },
        "importance": 8.5,
        "expected": "✅ highly relevant"
    },
    {
        "id": 3,
        "title": "French startup raises 10M€ to disrupt logistics industry",
        "topic": "business",
        "summary": "A French startup founded in 2024 has secured 10 million euros in seed funding from venture capital firms to scale its AI-powered logistics optimization platform. European tech entrepreneurship continues to grow strongly.",
        "topics": {
            "specific": ["seed funding", "venture capital", "logistics optimization", "entrepreneurship"],
            "generic":  ["startups", "business", "technology", "investment"]
        },
        "importance": 6.0,
        "expected": "✅ relevant"
    },
    {
        "id": 4,
        "title": "Tesla Autopilot: AI is redefining autonomous driving",
        "topic": "technology",
        "summary": "Tesla has significantly improved its Autopilot system using new artificial intelligence algorithms and computer vision techniques. Level 4 autonomous driving is approaching thanks to recent advances in machine learning and neural networks.",
        "topics": {
            "specific": ["Tesla Autopilot", "computer vision", "autonomous driving", "neural networks"],
            "generic":  ["artificial intelligence", "technology", "machine learning"]
        },
        "importance": 7.5,
        "expected": "✅ relevant"
    },
    {
        "id": 5,
        "title": "2028 Olympics: Los Angeles finalizes preparations",
        "topic": "sport",
        "summary": "Los Angeles is making steady progress in preparing for the 2028 Olympic Games. Sports infrastructure, transportation plans, and the Olympic village construction are on track to welcome athletes from around the world.",
        "topics": {
            "specific": ["Olympic Games", "Los Angeles", "sports infrastructure"],
            "generic":  ["sport", "events", "urban planning"]
        },
        "importance": 5.0,
        "expected": "❌ not relevant"
    },
    {
        "id": 6,
        "title": "Recipe: Classic French caramelized apple tarte tatin",
        "topic": "food",
        "summary": "Discover the traditional recipe for tarte tatin with caramelized apples. A crispy puff pastry base topped with golden butter-cooked apples and brown sugar, creating a delicious and easy-to-make dessert for the whole family.",
        "topics": {
            "specific": ["tarte tatin", "caramelized apples", "puff pastry", "dessert recipe"],
            "generic":  ["food", "cooking", "cuisine"]
        },
        "importance": 2.0,
        "expected": "❌ not relevant"
    },
    {
        "id": 7,
        "title": "European elections: key economic challenges ahead",
        "topic": "politics",
        "summary": "The upcoming European elections are focusing debate on fiscal policy, corporate taxation, and industrial sovereignty of the European Union in relation to the United States and China. Economic competitiveness is at the heart of every campaign.",
        "topics": {
            "specific": ["European elections", "fiscal policy", "corporate taxation", "industrial sovereignty"],
            "generic":  ["politics", "economics", "European Union"]
        },
        "importance": 7.0,
        "expected": "❌ not relevant"
    },
    {
        "id": 8,
        "title": "Nvidia announces revolutionary AI chip for data centers",
        "topic": "technology",
        "summary": "Nvidia has unveiled the H300 GPU specifically designed for training large AI models in data centers. This chip delivers 4x better performance for deep learning and LLM workloads, marking a major step forward for artificial intelligence infrastructure.",
        "topics": {
            "specific": ["Nvidia H300", "GPU", "data center", "LLM training", "deep learning"],
            "generic":  ["artificial intelligence", "technology", "hardware"]
        },
        "importance": 9.0,
        "expected": "✅ highly relevant"
    },
    {
        "id": 9,
        "title": "Climate change: record temperatures hit Europe this summer",
        "topic": "environment",
        "summary": "Europe experienced its hottest summer on record in 2026, with temperatures exceeding 45°C in several countries. Scientists warn that without urgent action on carbon emissions, extreme heat events will become the new normal by 2040.",
        "topics": {
            "specific": ["carbon emissions", "extreme heat", "climate science", "global warming"],
            "generic":  ["environment", "climate change", "science"]
        },
        "importance": 8.0,
        "expected": "❌ not relevant"
    },
    {
        "id": 10,
        "title": "Y Combinator's latest batch features 40% AI startups",
        "topic": "business",
        "summary": "Y Combinator's Summer 2026 batch includes a record 40% of AI-focused startups, reflecting the dominance of artificial intelligence in early-stage venture funding. Founders are building LLM-powered tools across healthcare, legal, and finance sectors.",
        "topics": {
            "specific": ["Y Combinator", "early-stage funding", "LLM-powered tools", "venture funding"],
            "generic":  ["startups", "artificial intelligence", "business", "entrepreneurship"]
        },
        "importance": 7.5,
        "expected": "✅ highly relevant"
    },
]

# ─── STEP 1 — PROFILE STRUCTURING ─────────────────────────

def structure_interests(interests: list) -> dict:
    """
    Ask Groq to classify interests as specific, generic, or redundant.
    Redundant = already fully covered by a more specific interest.
    """
    response = groq_client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {
                "role": "system",
                "content": (
                    "You are an interest taxonomy expert. "
                    "Respond ONLY with a valid JSON object, no explanation, no markdown."
                )
            },
            {
                "role": "user",
                "content": (
                    f"Given these user interests: {interests}\n\n"
                    "Classify each interest into exactly one category:\n"
                    "- specific: narrow, precise topic that cannot contain the others (e.g. 'machine learning', 'seed funding', 'artificial intelligence', 'startups')\n"
                    "- generic: broad umbrella term that contains or overlaps multiple other interests in the list (e.g. 'technology' contains 'AI' and 'startups')\n"
                    "- redundant: interest that is ENTIRELY covered by another MORE SPECIFIC interest already in the list. This is rare.\n\n"
                    "Rules:\n"
                    "- A generic term like 'tech innovation' or 'technology' should be classified as generic, not redundant\n"
                    "- A specific term like 'artificial intelligence' or 'startups' should be classified as specific, even if a generic term covers it\n"
                    "- Only mark as redundant if two interests mean almost exactly the same thing\n"
                    "- When in doubt, classify as specific\n\n"
                    "Return this exact JSON structure:\n"
                    "{\n"
                    '  "specific": ["interest1"],\n'
                    '  "generic": ["interest2"],\n'
                    '  "redundant": ["interest3"]\n'
                    "}"
                )
            }
        ],
        temperature=0.1,
        max_tokens=200
    )
    raw = response.choices[0].message.content.strip()
    # Strip markdown code fences if present
    raw = raw.replace("```json", "").replace("```", "").strip()
    return json.loads(raw)


# ─── STEP 2 — INTEREST ENRICHMENT ─────────────────────────

def enrich_interest(interest: str, kind: str) -> str:
    """
    Enrich an interest with keywords via Groq.
    Generic interests explicitly exclude terms already covered by specific ones.
    """
    specificity_note = (
        "Focus on very precise, narrow sub-topics, tools, models, companies, and techniques."
        if kind == "specific"
        else
        "Focus on broad domain labels, umbrella concepts, and adjacent fields. "
        "Avoid very technical or narrow terms — those are handled separately."
    )

    response = groq_client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {
                "role": "system",
                "content": (
                    "You are a keyword generation expert for semantic search.\n"
                    "Respond ONLY with a comma-separated list of keywords. "
                    "No sentences, no explanations, no numbering."
                )
            },
            {
                "role": "user",
                "content": (
                    f'Topic: "{interest}" ({kind})\n\n'
                    f"{specificity_note}\n\n"
                    "Generate 30 to 40 highly relevant keywords.\n"
                    "Format: keyword1, keyword2, keyword3, ..."
                )
            }
        ],
        temperature=0.3,
        max_tokens=300
    )
    return response.choices[0].message.content.strip()


# ─── STEP 3 — EMBEDDINGS ──────────────────────────────────

def get_embedding(text: str) -> np.ndarray:
    """Embedding via Gemini API"""
    time.sleep(0.5)  # avoid rate limit
    result = gemini_client.models.embed_content(
        model=MODEL_EMBED,
        contents=text
    )
    return np.array(result.embeddings[0].values)


def embed_keyword_list(keywords: list) -> np.ndarray:
    """Embed a list of keywords as a single joined text"""
    text = ", ".join(keywords)
    return get_embedding(text)


def build_profile_vectors(structured: dict, enriched: dict) -> dict:
    """
    Build one embedding vector per interest category (specific / generic).
    Each is a weighted average of enriched interest embeddings.
    Redundant interests are skipped.
    """
    vectors = {"specific": [], "generic": []}

    for kind in ["specific", "generic"]:
        for interest in structured.get(kind, []):
            emb = get_embedding(enriched[interest])
            vectors[kind].append(emb)

    # Average per category
    result = {}
    for kind in ["specific", "generic"]:
        if vectors[kind]:
            avg = np.mean(vectors[kind], axis=0)
            result[kind] = avg / np.linalg.norm(avg)
        else:
            result[kind] = None

    return result


# ─── STEP 4 — SCORING ─────────────────────────────────────

def cosine_similarity(v1: np.ndarray, v2: np.ndarray) -> float:
    norm = np.linalg.norm(v1) * np.linalg.norm(v2)
    return float(np.dot(v1, v2) / norm) if norm else 0.0


def score_article(article: dict, profile_vectors: dict) -> dict:
    """
    Multi-dimensional scoring:
    - specific_score : article.specific topics vs profile.specific vector
    - generic_score  : article.generic topics vs profile.generic vector
    - importance     : global importance weight
    """

    # Embed article topic keywords
    art_specific_emb = embed_keyword_list(article["topics"]["specific"])
    art_generic_emb  = embed_keyword_list(article["topics"]["generic"])

    # Specific vs Specific
    if profile_vectors["specific"] is not None:
        specific_score = cosine_similarity(art_specific_emb, profile_vectors["specific"])
    else:
        specific_score = 0.0

    # Generic vs Generic
    if profile_vectors["generic"] is not None:
        generic_score = cosine_similarity(art_generic_emb, profile_vectors["generic"])
    else:
        generic_score = 0.0

    importance = article["importance"] / 10.0

    # Specific match weighted higher — more precise signal
    final = (specific_score * 0.55) + (generic_score * 0.25) + (importance * 0.20)

    return {
        "specific_score": round(specific_score, 3),
        "generic_score":  round(generic_score, 3),
        "importance":     round(importance, 3),
        "final":          round(final, 3)
    }


# ─── MAIN ─────────────────────────────────────────────────

def main():
    print("=" * 70)
    print("  SEMANTIC MATCHING V4 — STRUCTURED PROFILE + TOPIC-LEVEL MATCHING")
    print("=" * 70)

    # ── Step 1: Structure profile ──
    print(f"\n👤 Raw interests: {USER_INTERESTS_RAW}")
    print("\n🧠 Structuring profile via Groq...")
    structured = structure_interests(USER_INTERESTS_RAW)
    print(f"   ✅ Specific  : {structured.get('specific', [])}")
    print(f"   🔵 Generic   : {structured.get('generic', [])}")
    print(f"   ❌ Redundant : {structured.get('redundant', [])}")

    # ── Step 2: Enrich non-redundant interests ──
    print("\n🔑 Enriching interests via Groq...\n")
    enriched = {}
    all_active = structured.get("specific", []) + structured.get("generic", [])

    for interest in all_active:
        kind = "specific" if interest in structured.get("specific", []) else "generic"
        keywords = enrich_interest(interest, kind)
        enriched[interest] = keywords
        print(f"   [{kind}] '{interest}'\n   → {keywords[:100]}...\n")

    # ── Step 3: Build profile vectors ──
    print("⏳ Building profile vectors (Gemini embeddings)...")
    profile_vectors = build_profile_vectors(structured, enriched)
    for kind, vec in profile_vectors.items():
        status = f"{len(vec)} dims" if vec is not None else "none"
        print(f"   ✓ {kind} profile vector : {status}")

    # ── Step 4: Score articles ──
    print("\n⏳ Scoring articles...\n")
    print("-" * 70)

    results = []
    for article in ARTICLES:
        scores = score_article(article, profile_vectors)
        results.append({**article, **scores})

    # ── Step 5: Fixed thresholds ──
    THRESH_HIGH = 0.72
    THRESH_LOW  = 0.62

    print(f"📐 Fixed thresholds")
    print(f"   🟢 Highly relevant : >= {THRESH_HIGH}")
    print(f"   🟡 Relevant        : >= {THRESH_LOW}")
    print(f"   🔴 Filtered        :  < {THRESH_LOW}\n")

    # ── Step 6: Display results ──
    results_sorted = sorted(results, key=lambda x: x["final"], reverse=True)

    print(f"{'Final':<7} {'Specific':<10} {'Generic':<10} {'Import':<8} {'Label':<20} Title")
    print("-" * 70)

    for r in results_sorted:
        f = r["final"]
        if f >= THRESH_HIGH:
            label = "🟢 highly relevant"
        elif f >= THRESH_LOW:
            label = "🟡 relevant"
        else:
            label = "🔴 not relevant"

        title = r["title"][:28] + "..." if len(r["title"]) > 28 else r["title"]
        print(f"{f:<7} {r['specific_score']:<10} {r['generic_score']:<10} {r['importance']:<8} {label:<20} {title}")
        print(f"        Expected: {r['expected']}\n")

    # ── Summary ──
    print("-" * 70)
    shown   = [r for r in results if r["final"] >= THRESH_LOW]
    filtered = [r for r in results if r["final"] < THRESH_LOW]

    print(f"\n📊 Summary:")
    print(f"   🟢 Shown in feed : {len(shown)} / {len(ARTICLES)}")
    print(f"   🔴 Filtered out  : {len(filtered)} / {len(ARTICLES)}")

    print(f"\n✅ User feed:")
    for r in sorted(shown, key=lambda x: x["final"], reverse=True):
        print(f"   {r['final']}  [{r['specific_score']} spec / {r['generic_score']} gen]  {r['title']}")

    print(f"\n❌ Filtered articles:")
    for r in sorted(filtered, key=lambda x: x["final"], reverse=True):
        print(f"   {r['final']}  [{r['specific_score']} spec / {r['generic_score']} gen]  {r['title']}")


if __name__ == "__main__":
    main()